apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate an empty configmap, to be replaced in overlays, to help
# kustomize know how to update configMapKeyRefs
configMapGenerator:
- name: redis

- name: redis-r8-scripts
  files:
  - reload-certs.sh

# Generate empty secrets, to be replaced in overlays, to help
# kustomize know how to update secretKeyRefs
secretGenerator:
- name: redis
  type: Opaque
  options:
    disableNameSuffixHash: true


configurations:
- name-prefix.yaml
- servicemonitor-selector.yaml

resources:
- certificate.yaml
- prometheus-ingress-networkpolicy.yaml
- reload-redis-certs.yaml
- service-monitor.yaml
