{{- range $_index, $server := .Values.valkey.servers }}
{{- if and (hasKey $server "tls") (hasKey $server.tls "enabled") (eq $server.tls.enabled true) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: valkey-server-tls-{{ $server.name }}-{{ .Release.Name }}
spec:
  secretName: {{ default (printf "valkey-server-tls-%s-%s" $server.name .Release.Name) $server.tls.secretName }}
  issuerRef:
    name: issuer
    kind: GoogleCASClusterIssuer
    group: cas-issuer.jetstack.io
  renewBefore: 8h
  duration: 24h 
  dnsNames:
  - valkey-server-{{ $server.name }}-{{ .Release.Name }}
  - valkey-server-{{ $server.name }}-{{ .Release.Name }}.{{ .Release.Namespace }}
  - valkey-server-{{ $server.name }}-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
  - valkey-server-{{ $server.name }}-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local.
{{- end }}
{{- end }}
