{{- range $_index, $server := .Values.valkey.servers }}
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-server-{{ $server.name }}-{{ $.Release.Name }}
spec:
  selector:
    app.kubernetes.io/component: valkey-server
    app.kubernetes.io/instance: {{ $server.name }}-{{ $.Release.Name }}
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: valkey
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
{{- end }}
