{{- if and (hasKey $.Values.sentinel "tls") (hasKey $.Values.sentinel.tls "enabled") (eq $.Values.sentinel.tls.enabled true) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: valkey-sentinel-tls
  namespace: {{ $.Values.global.namespace }}
spec:
  secretName: {{ default "valkey-sentinel-tls" $.Values.sentinel.tls.secretName }}
  issuerRef:
    name: issuer
    kind: GoogleCASClusterIssuer
    group: cas-issuer.jetstack.io
  renewBefore: 8h
  duration: 24h 
  dnsNames:
  - valkey-sentinel
  - valkey-sentinel.{{ $.Values.global.namespace }}
  - valkey-sentinel.{{ $.Values.global.namespace }}.svc.cluster.local
  - valkey-sentinel.{{ $.Values.global.namespace }}.svc.cluster.local.
{{- end }}
