{{- if and (hasKey $.Values.sentinel "tls") (hasKey $.Values.sentinel.tls "enabled") (eq $.Values.sentinel.tls.enabled true) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: valkey-sentinel-tls-{{ .Release.Name }}
spec:
  secretName: {{ default "valkey-sentinel-tls" $.Values.sentinel.tls.secretName }}
  issuerRef:
    name: issuer
    kind: GoogleCASClusterIssuer
    group: cas-issuer.jetstack.io
  renewBefore: 8h
  duration: 24h 
  dnsNames:
  - valkey-sentinel-{{ .Release.Name }}
  - valkey-sentinel-{{ .Release.Name }}.{{ .Release.Namespace }}
  - valkey-sentinel-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
  - valkey-sentinel-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local.
{{- end }}
