apiVersion: v1
kind: Service
metadata:
  name: valkey-sentinel-{{ .Release.Name }}
  labels:
    app.kubernetes.io/component: valkey-sentinel
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: valkey-sentinel
    app.kubernetes.io/part-of: valkey
spec:
  selector:
    app.kubernetes.io/component: valkey-sentinel
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: valkey-sentinel
    app.kubernetes.io/part-of: valkey
  ports:
    - name: sentinel
      port: 26379
      targetPort: 26379
  type: ClusterIP
