apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey-sentinel
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: valkey-sentinel
    app.kubernetes.io/component: valkey-sentinel
    app.kubernetes.io/part-of: valkey
spec:
  serviceName: valkey-sentinel
  replicas: {{ default 3 .Values.sentinel.replicas | int }}
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey-sentinel
      app.kubernetes.io/component: valkey-sentinel
      app.kubernetes.io/part-of: valkey
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valkey-sentinel
        app.kubernetes.io/component: valkey-sentinel
        app.kubernetes.io/part-of: valkey
    spec:
      securityContext:
        fsGroup: 1000

      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: valkey-sentinel
              app.kubernetes.io/component: valkey-sentinel
              app.kubernetes.io/part-of: valkey
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule

      initContainers:
      - name: init-sentinel
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: alpine:latest
        command: ["sh", "-c"]
        args:
        - |
          if [ ! -f /data/sentinel.conf ]; then
            echo "sentinel resolve-hostnames yes" >> /data/sentinel.conf
            echo "sentinel announce-hostnames yes" >> /data/sentinel.conf
            echo "sentinel announce-ip ${POD_NAME}.valkey-sentinel.valkey.svc.cluster.local" >> /data/sentinel.conf
            #echo "sentinel requirepass {{ .Values.sentinel.password }}" >> /data/sentinel.conf
            chown 999:1000 /data/sentinel.conf
          fi

        volumeMounts:
          - name: data
            mountPath: /data

      containers:
      - name: valkey-sentinel
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VALKEY_NODE_TYPE
          value: "sentinel"
        - name: VALKEY_PORT
          value: "26379"
        {{- if and (hasKey $.Values.sentinel "tls") (hasKey $.Values.sentinel.tls "enabled") (eq $.Values.sentinel.tls.enabled true) }}
        - name: VALKEY_TLS_ENABLED
          value: "true"
        {{- end }}
        image: {{ default "valkey/valkey:8.1-alpine" $.Values.sentinel.image }}
        imagePullPolicy: IfNotPresent

        args: 
        - /usr/local/bin/valkey-sentinel
        - /data/sentinel.conf

        securityContext:
          runAsUser: 999
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]

        volumeMounts:
        - name: data
          mountPath: /data

        resources:
          requests:
            cpu: 10m
            memory: 32Mi

  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.sentinel.storage.size }}
