apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey-sentinel-{{ .Release.Name }}
  labels:
    app.kubernetes.io/component: valkey-sentinel
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: valkey-sentinel
    app.kubernetes.io/part-of: valkey
spec:
  serviceName: valkey-sentinel-{{ .Release.Name }}
  replicas: {{ default 3 .Values.sentinel.replicas | int }}
  selector:
    matchLabels:
      app.kubernetes.io/component: valkey-sentinel
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: valkey-sentinel
      app.kubernetes.io/part-of: valkey
  template:
    metadata:
      labels:
        app.kubernetes.io/component: valkey-sentinel
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: valkey-sentinel
        app.kubernetes.io/part-of: valkey
    spec:
      securityContext:
        fsGroup: 1000

      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: valkey-sentinel
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/name: valkey-sentinel
              app.kubernetes.io/part-of: valkey
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule

      initContainers:
      - name: init-sentinel
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.sentinel.password_secret }}
              key: password
        - name: REDISCLI_AUTH
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.sentinel.password_secret }}
              key: password
        image: alpine:latest
        command: ["sh", "-c"]
        args:
        - |
          if [ ! -f /data/sentinel.conf ]; then
            echo "sentinel resolve-hostnames yes" >> /data/sentinel.conf
            echo "sentinel announce-hostnames yes" >> /data/sentinel.conf
            echo "sentinel announce-ip ${POD_NAME}.valkey-sentinel-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local" >> /data/sentinel.conf
            echo "requirepass ${VALKEY_PASSWORD}" >> /data/sentinel.conf
            echo "masterauth ${VALKEY_PASSWORD}" >> /data/sentinel.conf
            chown 999:1000 /data/sentinel.conf
          fi

        volumeMounts:
          - name: data
            mountPath: /data

      containers:
      - name: valkey-sentinel
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VALKEY_NODE_TYPE
          value: "sentinel"
        - name: VALKEY_PORT
          value: "26379"
        {{- if and (hasKey $.Values.sentinel "tls") (hasKey $.Values.sentinel.tls "enabled") (eq $.Values.sentinel.tls.enabled true) }}
        - name: VALKEY_TLS
          value: "true"
        - name: VALKEY_CACERT
          value: /opt/valkey/etc/certs/ca.crt
        - name: VALKEY_CERT_FILE
          value: /opt/valkey/etc/certs/tls.crt
        - name: VALKEY_KEY_FILE
          value: /opt/valkey/etc/certs/tls.key
        {{- end }}
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.sentinel.password_secret }}
              key: password
        - name: REDISCLI_AUTH
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.sentinel.password_secret }}
              key: password
        image: {{ default "valkey/valkey:8.1-alpine" $.Values.sentinel.image }}
        imagePullPolicy: IfNotPresent

        args: 
        - /usr/local/bin/valkey-sentinel
        - /data/sentinel.conf
        {{- if and (hasKey $.Values.sentinel "tls") (hasKey $.Values.sentinel.tls "enabled") (eq $.Values.sentinel.tls.enabled true) }}
        - --tls
        - --tls-ca-file ${VALKEY_CACERT}
        - --tls-cert-file ${VALKEY_CERT_FILE}
        - --tls-key-file ${VALKEY_KEY_FILE}
        {{- end }}

        securityContext:
          runAsUser: 999
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]

        volumeMounts:
        - name: data
          mountPath: /data
        {{- if and (hasKey $.Values.sentinel "tls") (hasKey $.Values.sentinel.tls "enabled") (eq $.Values.sentinel.tls.enabled true) }}
        - name: certs
          mountPath: /opt/valkey/etc/certs
        {{- end }}

        resources:
          requests:
            cpu: 10m
            memory: 32Mi

      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        args: ['--skip-tls-verification=true']
        ports:
          - containerPort: 9121
            name: redis-exporter
        env:
          - name: REDIS_ALIAS
            value: "redis"
          - name: REDIS_ADDR
            value: "rediss://localhost:6379"
          - name: REDIS_USER
            value: "default"
          {{- if and (hasKey $.Values.sentinel "tls") (hasKey $.Values.sentinel.tls "enabled") (eq $.Values.sentinel.tls.enabled true) }}
          - name: REDIS_EXPORTER_TLA_CA_CERT_FILE
            value: /opt/valkey/etc/certs/ca.crt
          {{- end }}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.sentinel.password_secret }}
                key: password
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: metrics
          timeoutSeconds: 5
        name: metrics
        ports:
        - containerPort: 9121
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 150m
            ephemeral-storage: 2Gi
            memory: 192Mi
          requests:
            cpu: 100m
            ephemeral-storage: 50Mi
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seLinuxOptions: {}
          seccompProfile:
            type: RuntimeDefault

      volumes:
      - name: certs
        secret:
          secretName: valkey-sentinel-tls-{{ .Release.Name }}

  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.sentinel.storage.size }}
