apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: redis
  repo: oci://registry-1.docker.io/bitnamicharts
  releaseName: redis
  namespace: default
  version: 17.11.3
  valuesFile: values.yaml
