---
apiVersion: v1
kind: Namespace
metadata:
  name: valkey
---
apiVersion: v1
kind: Secret
metadata:
  namespace: valkey
  name: valkey-sentinel-password
type: Opaque
data:
  password: Ym9ndXNib2d1c2JvZ3Vz
---
apiVersion: v1
kind: Secret
metadata:
  namespace: valkey
  name: valkey-server-omg-password
type: Opaque
data:
  password: Ym9ndXNpc2xpZmU=
---
apiVersion: v1
kind: Pod
metadata:
  namespace: valkey
  name: valkey-client-test
spec:
  containers:
    - env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: valkey-server-omg-password
      name: valkey-client-test
      image: valkey/valkey:8.1-alpine
      resources:
        limits:
          cpu: "1"
          memory: 100Mi
      command: [sleep, "3600"]
