#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

CURRENT_CONTEXT="$(kubectl config current-context)"

case "${CURRENT_CONTEXT}" in
kind-kind | kind-chart-testing)
    : this is fine
    ;;
*)
    printf 'Refusing to run in "%s" context (expecting "kind-kind")\n' "${CURRENT_CONTEXT}" >&2
    exit 86
    ;;
esac

cleanup() {
    kubectl delete -f script/.test-resources.yaml
}

trap cleanup QUIT TERM EXIT

kind load docker-image docker.io/kustomize-components/valkey:local
kubectl apply -f script/.test-resources.yaml
uv run ct install \
    --chart-dirs . \
    --charts valkey \
    --debug \
    --helm-extra-args '--timeout=600s' \
    --namespace valkey
