#!/bin/bash
set -euo pipefail

# source the functions
# shellcheck source=/dev/null
. /opt/valkey/entrypoint/functions

wait_for_valkey

echo "Waiting for Valkey Sentinel to be ready"
wait_for_sentinel "valkey-sentinel" "26379"

SENTINEL_QUORUM=$(get_sentinel_quorum "${VALKEY_REQUIRED_SENTINELS}")

echo "Discovering Valkey Master via Sentinel"
MASTER=$(get_master_addr_by_name "valkey-sentinel" "${VALKEY_NAME}")

# StatefulSets only start one pod at a time, so we can safely assume if there is no master, we are the first pod
if [[ "${MASTER}" == "null" ]]; then
    echo "No Master found, configuring self as master"
    while true; do
        REQUIRED_SENTINELS="${VALKEY_REQUIRED_SENTINELS}"
        mapfile -t SENTINELS < <(dig +short SRV "${VALKEY_SENTINEL_SERVICE_SRV}" | awk '{ print $4 }' | sort -u)
        SENTINEL_COUNT="${#SENTINELS[@]}"
        if ((SENTINEL_COUNT >= REQUIRED_SENTINELS)); then
            echo "Found ${SENTINEL_COUNT} Sentinels, proceeding with the setup."
            break
        else
            echo "Waiting for more Sentinels to come up... (found ${SENTINEL_COUNT}, waiting for ${REQUIRED_SENTINELS})"
            sleep 1
        fi
    done

    # shellcheck disable=SC2086,SC2154
    valkey-cli $common_args -p 6379 REPLICAOF no one
    echo "Notifying all Sentinels"

    # Get the list of Sentinel IPs from SRV records
    mapfile -t SENTINELS_LIST < <(dig +short SRV "${VALKEY_SENTINEL_SERVICE_SRV}" | awk '{ print $4 }')
    echo "Sentinel quorum: ${SENTINEL_QUORUM}"
    [[ "${VALKEY_DOWN_AFTER_MILLISECONDS}" -ne "0" ]] && echo "Setting down-after-milliseconds to ${VALKEY_DOWN_AFTER_MILLISECONDS}"
    [[ "${VALKEY_FAILOVER_TIMEOUT}" -ne "0" ]] && echo "Setting failover-timeout to ${VALKEY_FAILOVER_TIMEOUT}"
    [[ "${VALKEY_PARALLEL_SYNCS}" -ne "0" ]] && echo "Setting parallel-syncs to ${VALKEY_PARALLEL_SYNCS}"
    for SENTINEL in "${SENTINELS_LIST[@]}"; do
        FQDN="${HOSTNAME}.${VALKEY_SERVICE_NAME}.${NAMESPACE_NAME:-valkey}.svc.cluster.local"
        echo "Notifying Sentinel at ${SENTINEL} master of ${VALKEY_NAME} at '${FQDN}'"
        run_sentinel_cmd "${SENTINEL}" monitor "${VALKEY_NAME}" "${FQDN}" 6379 "${SENTINEL_QUORUM}"
        if [[ "${VALKEY_DOWN_AFTER_MILLISECONDS}" -ne "0" ]]; then
            run_sentinel_cmd "${SENTINEL}" set "${VALKEY_NAME}" down-after-milliseconds "${VALKEY_DOWN_AFTER_MILLISECONDS}"
        fi
        if [[ "${VALKEY_FAILOVER_TIMEOUT}" -ne "0" ]]; then
            run_sentinel_cmd "${SENTINEL}" set "${VALKEY_NAME}" failover-timeout "${VALKEY_FAILOVER_TIMEOUT}"
        fi
        if [[ "${VALKEY_PARALLEL_SYNCS}" -ne "0" ]]; then
            run_sentinel_cmd "${SENTINEL}" set "${VALKEY_NAME}" parallel-syncs "${VALKEY_PARALLEL_SYNCS}"
        fi
        run_sentinel_cmd "${SENTINEL}" set "${VALKEY_NAME}" auth-pass "${VALKEY_PASSWORD}"
    done
else
    until [[ "${MASTER}" != "null" ]]; do
        sleep 1
        echo "No Master found, attempting to discover it via Sentinel"
        MASTER=$(get_master_addr_by_name "valkey-sentinel" "${VALKEY_NAME}")
    done
    MASTER_ADDR=$(echo "${MASTER}" | jq -r '.[0]')
    MASTER_PORT=$(echo "${MASTER}" | jq -r '.[1]')

    echo "Master found: ${MASTER_ADDR}:${MASTER_PORT}"
    echo "Sending 'REPLICAOF ${MASTER_ADDR} ${MASTER_PORT}' to local Valkey"
    # shellcheck disable=SC2086
    valkey-cli $common_args -p 6379 REPLICAOF "${MASTER_ADDR}" "${MASTER_PORT}"
fi

touch /opt/valkey/etc/ready
echo "Valkey Server is ready"
exit 0
