apiVersion: v2
appVersion: 8.1
description: Replicate Specific Valkey Setup
home: https://github.com/replicate/kustomize-components/
sources:
- https://github.com/replicate/kustomize-components/tree/main/valkey
name: valkey
version: 1.0.1
