sentinel:
  image: docker.io/kustomize-components/valkey:local
  storage:
    size: 100Mi
  replicas: 3
  password_secret: valkey-sentinel-password

valkey:
  image: docker.io/kustomize-components/valkey:local
  servers:
  - name: testme
    password_secret: valkey-server-omg-password
    replicas: 2
    maxmemory: 95mb
    storage:
      size: 200Mi
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  - name: omg
    replicas: 2
    down_after_milliseconds: 3000
    failover_timeout: 10000
    parallel_syncs: 1
    password_secret: valkey-server-omg-password
    maxmemory: 95mb
    storage:
      size: 200Mi
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
